### ISSUE TITLE
Add test suite for DRV8825

### ISSUE THREAD

**Issue by hannobraun** [hannobraun/stepper#44]
We now have a test stand in the repository that runs a test suite for the STSPIN220. It would be great to also have a test suite for the DRV8825. I think for now it would be good enough to just add another test suite (modeled after the STSPIN220 test suite) and tell users to pass `-- test drv8825` or `--test stspin220`, depending on what they have available.

**Comment by hannobraun** [comment]
Largely blocked by #49.

**Comment by jessebraham** [comment]
I'm able to tackle this over the next few days if you feel it's still worth pursuing at this point. It's fairly derivative of the `STSPIN220` tests, so it shouldn't be too much effort.

**Comment by hannobraun** [comment]
I'd say it's worth pursuing if you're interested in the test stand and want to look into it at this point (as a learning experience, or to figure out how to make it work better, for example). If you're not interested in that, your time is probably better spent elsewhere, until someone builds a better test stand.

**Comment by hannobraun** [comment]
This library is no longer actively developed (and hasn't been for a while). I'm closing any issues that don't relate to specific gaps in existing functionality, as to not make the wrong impression about what is planned and desired.
